server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  security:
    filter:
      order: -100
    jwt:
      key: testPrivateKey
      expire: 7
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.164.12/assignment_6034
    username: root
    password: y6263309
  data:
    redis:
      host: 39.108.164.12
      port: 6379
      password: y6263309
  rabbitmq:
    addresses: 39.108.164.12
    username: root
    password: y6263309
    virtual-host: /test
    port: 5672
  mail:
    host: smtp.163.com
    username: 15160284336@163.com
    password: JACYFGHVJTVZFBRS
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory